config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :polls

  get 'welcome/faq'

  post 'votes/create/:id' => 'votes#create', as: 'vote_create'

  get '/poll/:id/r' => 'polls#results', as: 'poll_results'

   root 'polls#new'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessor :param_options, :charity_id, :text_options
  belongs_to :charity
  has_many :options
  has_many :votes
  validate :has_options
  validates_presence_of :question

  def has_voted(user_or_uid)
    if user_or_uid.blank?
      return false
    end

    user_id = user_or_uid.respond_to?(:id) ? user_or_uid.id : user_or_uid

    return Vote.verified.where({user_id: user_id, poll_id: self.id}).count > 0    
  end

  def results
    rows = ActiveRecord::Base.connection.exec_query("SELECT COUNT(v.id) as votes, o.name, o.id
      FROM options o
      LEFT JOIN votes v
      ON v.option_id = o.id
      AND v.verified = 't'
      GROUP BY v.option_id
      ORDER BY votes DESC")
    results = []
    total_votes = self.total_votes

    rows.each do |r|
      results.push({votes: r['votes'], name: r['name'], option_id: r['id'], percentage: 100*(r['votes'].to_f / total_votes.to_f)})
    end

    return results
  end

  def total_votes
    self.votes.verified.count
  end

  def has_options
    num_options = 0
    msg = ""
    self.text_options = []

    if !param_options.nil?
      (0..3).each do |i|
        option_text = param_options[i.to_s].to_s
        if !option_text.empty? && num_options < 5
          num_options = num_options + 1
        end
        self.text_options.push(option_text)
      end
    end

    if num_options < 2
      errors.add(:base, "You must provide at least 2 options")
    end
  end

  def save_text_options
    self.text_options.each do |a|
      self.options.create({name: a})
    end
    self.text_options = []
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy, :submit_vote]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @vote_form = VoteForm.new
    @vote_form.poll_id = @poll.id
    @page_title = @poll.question
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    @text_options = ["","","",""]
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)
    @poll.param_options = params[:text_options]

    respond_to do |format|
      if @poll.save && @poll.save_text_options
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        @text_options = @poll.text_options
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:question)
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.haml
= simple_form_for(@poll) do |f|
	= render 'shared/error_messages', object: f.object
	= f.input :question
	.options
		-i = 0
		-@text_options.each do |t|
			= f.input :text_options, label: "#{i+1}.", input_html: {id: "option_#{i}", name: "text_options[#{i}]", value: t}
			-i = i + 1

	= f.association :charity, label: "Default Charity"

	= f.button :button

app/views/polls/_results.html.haml
-results = poll.results
-bar_classes = ['info','success','','warning','danger']
.poll-results
	%ol.results
		- i = -1
		-results.each do |r|
			- i += 1
			%li.result
				.name= r[:name]
				.numbers
					%span.num-votes #{pluralize(r[:votes], 'vote')}
					%span.percentage (#{r[:percentage].round(1)}%)
				.progress
					.progress-bar{role: "progressbar", style: "width: #{r[:percentage]}%;", "class" => "progress-bar-#{bar_classes[i]}"}
	.vote-count Total Votes: #{poll.total_votes}

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.haml
%h1 Polls

%ul
	-@polls.each do |p|
		%li= link_to(p.question, p)

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

app/views/polls/show.html.haml
-content_for :title, @poll.question
%h1= @poll.question
-if !@poll.has_voted(@user)
	=simple_form_for @vote_form, url: vote_create_path(@poll) do |f|
		=f.input :poll_id, as: "hidden"
		= render 'shared/error_messages', object: @vote_form
		= render 'votes/option_fields', {poll: @poll, option_id: @vote_form.option_id}

		-if !user_signed_in?
			=f.collection_radio_buttons :user_login_or_register, [["login", "I already have an account"],["register", "I am a new user"]], :first, :last

			.user-fields
				=f.input :user_email, label: "Email"
				=f.input :user_password, label: "Password"
				=f.input :user_password_confirmation, label: "Confirm Password"

		=f.button :button, (user_signed_in? ? "Vote" : "Login & Vote"), id: "submit-button"
-else
	.col-md-9
		= render "results", poll: @poll
	.col-md-3

:javascript
	$('body').ready(function () {
		console.log("sup");
		$('input[name="vote_form[user_login_or_register]"]').change(function () {
			var val = $(this).val();
			if(val == 'login') {
				$('#submit-button').text('Login & Vote');
				$('.vote_form_user_password_confirmation').hide();
			}
			else {
				$('#submit-button').text('Register & Vote');
				$('.vote_form_user_password_confirmation').show();
			}
		}).trigger('change');
	});